name: Render Deploy
on:
  push:
env:
  RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: actions/checkout@v1